version: '2'

services:
  db:
    image: mariadb:10.3
    env_file:
      - .env.docker
    expose:
      - 3306
    networks:
      - backend-network

  backend:
    build: .
    command: npm start
    env_file:
      - .env.docker
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    links:
      - db
    networks:
      - backend-network

networks:
    backend-network:
        driver: bridge


